---
- name: locate
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  tasks:
  - name: installation de locate
    apt: name=apache2 state=absent
    
    
    
    
