---
- name: Apache 2
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  tasks:
  - name: remove Apache 2
    apt: name=apache2 state=absent autoremove=yes force=yes purge=yes
    
    
    
    
